### ISSUE TITLE
using embeddings?

### ISSUE THREAD

**Issue by rahulvramesh** [fboulnois/stable-diffusion-docker#50]
Hi,

is it possible to use the embeddings with the setup?

**Comment by fboulnois** [comment]
Not for training, however if you create a new model that includes the embedding you can specify it using `--model`. For example, [openjourney](prompthero/openjourney) and [dreamlike-diffusion](https://huggingface.co/dreamlike-art/dreamlike-diffusion-1.0) both have embeddings and work out-of-the-box since as far as the pipeline is concerned they're just like any other model.

Watch for changes in the README.md when #49 goes in!

**Comment by rahulvramesh** [comment]
@fboulnois thanks, will be looking forward to it.
